services:
  # Backend API Service
  - type: web
    name: trial-2-5mv8-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://trial-2-5mv8.onrender.com

  # Frontend Service
  - type: web
    name: frosstbank-frontend
    env: static
    plan: free
    buildCommand: echo "Static files already built"
    staticPublishPath: ./frontend
    envVars:
      - key: BACKEND_URL
        value: https://trial-1-sq1y.onrender.com 